### ISSUE TITLE
你当我们是傻逼吗？

### ISSUE THREAD

**Issue by cjim8889** [996icu007/996.icu.to.007#3]
信用卡套现风险这么大，房产还是不动产liquidity非常低。你这方法迟早进牢。

**Comment by wangcongyi** [comment]
@cjim8889  快速发财致富的方法 都写在刑法上啦~~  哈哈哈~~~

**Comment by 996icu007** [comment]
如果早四五年，有哪个“傻逼”告诉我有这条路，我现在至少在一线城市有两套以上的房子了。对，我现在没房，就是太迟知道这方法，整天只用自己的工资来衡量房价。
拜托你去查查法律地恶意透支的定义，再了解下目前有多少人在tx，这已经是一个大而不能倒的行业。
耶稣说：“不要把神圣的东西丢给狗，它们会转过头来咬你们；不要把珍珠扔给猪， 它们会把珍珠践踏在脚底下。”
说得还真tm对。

**Comment by sonyzhang** [comment]
那么请问，如何大幅提升信用卡额度呢？

**Comment by 996icu007** [comment]
> 那么请问，如何大幅提升信用卡额度呢？

没有快速的方法，但是早一天知道这方法就能早一天准备，早日了解清楚也能让你避免踩一些坑。

**Comment by notfresh** [comment]
思路清奇
真的能玩？

**Comment by 996icu007** [comment]
> 思路清奇
> 真的能玩？
当然，我一个朋友只用半年，卡的总额度就已经增加了五六十万。
上士闻道，勤而行之；中士闻道，若存若亡；下士闻道，大笑之。
当我看到这句话时，我知道他原来就是”上士”，因为他不像有些sb，看到自己无法理解的东西或跟自己习惯思维有冲突的东西时，就认为对方是沙雕。

**Comment by notfresh** [comment]
你开始这种发家致富之道了吗？，等你好消息。


------------------ Original ------------------

**Comment by notfresh** [comment]
> > 思路清奇
> > 真的能玩？
> > 当然，我一个朋友只用半年，卡的总额度就已经增加了五六十万。
> > 上士闻道，勤而行之；中士闻道，若存若亡；下士闻道，大笑之。
> > 当我看到这句话时，我知道他原来就是”上士”，因为他不像有些sb，看到自己无法理解的东西或跟自己习惯思维有冲突的东西时，就认为对方是沙雕。

等给你好消息，求带。
